### ISSUE TITLE
Shuffle playlist bug

### ISSUE THREAD

**Issue by Klema4** [hernikplays/OcarinaPlayer#6]
**App will crash when you click few times on shuffle icon.**
- You can rework it when you click shuffle, and then you will click few times. Now you need to wait a second to crash the app. Or you just click once and it will crash too.
**[Video - Imgur](https://imgur.com/WJAh9bH)**

**Shuffle icon secondary color bug.**
- When you click on the icon, it will doesn't show my s
econdary color and still will remain blue.
**![image](https://user-images.githubusercontent.com/45459954/92328541-d688b980-f061-11ea-9168-48d64f15f6d6.png)**
**![image](https://user-images.githubusercontent.com/45459954/92328550-e0122180-f061-11ea-88f4-c8034828b804.png)**

**Comment by hernikplays** [comment]
Yeah, I forgot to change the color in the code to the config one, and also forgot a check if any files are in playlist :D 
Will fix it soon

**Comment by hernikplays** [comment]
Should be fixed with v0.3.1
