### ISSUE TITLE
Song time & slider freeze after mooving slider

### ISSUE THREAD

**Issue by Klema4** [hernikplays/OcarinaPlayer#7]
**When you playing a song, you might wanna move somewhere else in time, but then it will freeze and can't reload duration or auto moving slider.**
- Step to reproduce: Play file and then, move slider somewhere in the duration, it will stop doing its thing. You can unfreeze your slider & timer by restarting app (exit > start)
Showcase video: **[Video - Imgur](https://imgur.com/I8VQ3mm)**

**Comment by hernikplays** [comment]
This is a known bug, will try to fix it soon

**Comment by hernikplays** [comment]
Should be fixed with v0.3.1, lmk if it isn't fixed
